# Generated by Django 6.0.4 on 2026-05-06 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administradores', '0001_initial'),
        ('usuarios', '0002_remove_usuario_metodo_pago_preferido_carrito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenAPI',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_api', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Token API (Usuario)',
                'verbose_name_plural': 'Tokens API (Usuarios)',
            },
        ),
        migrations.CreateModel(
            name='TokenAPIAdmin',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('administrador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_api', to='administradores.administrador')),
            ],
            options={
                'verbose_name': 'Token API (Admin)',
                'verbose_name_plural': 'Tokens API (Admins)',
            },
        ),
    ]
