# Generated by Django 6.0.4 on 2026-04-29 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='metodo_pago_preferido',
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='TarjetaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_titular', models.CharField(max_length=100)),
                ('ultimos_cuatro', models.CharField(max_length=4)),
                ('tipo_tarjeta', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('otro', 'Otra')], default='otro', max_length=20)),
                ('mes_expiracion', models.CharField(max_length=2)),
                ('anio_expiracion', models.CharField(max_length=4)),
                ('es_predeterminada', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='usuarios.usuario')),
            ],
            options={
                'verbose_name_plural': 'Tarjetas de crédito',
                'ordering': ['-es_predeterminada', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='usuarios.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
            ],
            options={
                'unique_together': {('carrito', 'producto')},
            },
        ),
    ]
